/*
 * The MIT License (MIT)
 *
 * Copyright (c) 2023-2025 Daniel Alievsky, AlgART Laboratory (http://algart.net)
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

package net.algart.matrices.tiff.tests.misc;

import net.algart.matrices.tiff.TiffException;
import net.algart.matrices.tiff.TiffIFD;
import net.algart.matrices.tiff.tags.SvsDescription;

import java.time.LocalDateTime;

public class SvsDescriptionTest {
    private static void printDescription(TiffIFD ifd) {
        System.out.printf("optDescription: %s%n", ifd.optDescription());
        System.out.printf("getDescription: %s%n", ifd.getDescription());
        System.out.println(ifd.toString(TiffIFD.StringFormat.NORMAL));
        System.out.println();
    }

    public static void main(String[] args) throws TiffException {
        TiffIFD ifd = new TiffIFD();
        ifd.putImageDimensions(10000, 10000);
        ifd.defaultTileSizes();
        SvsDescription.Builder builder = new SvsDescription.Builder();
        builder.applicationSuffix("10.0");
        builder.updateFrom(ifd, true);
        builder.autoGeneratedSummary(true);
        builder.compressionName("JPEG/RGB");
        builder.quality(30);
        builder.pixelSize(0.45);
        builder.magnification(20);
        ifd.putDescription(builder.build());
        printDescription(ifd);

        builder.autoGeneratedSummary(false)
                .summary("My summary");
        System.out.printf("Description 2:%n%s%n%n", builder.build().toString(TiffIFD.StringFormat.NORMAL));

        builder.autoGeneratedSummary(true)
                .scanOffsetX(123)
                .dateTime(LocalDateTime.now());
        System.out.printf("Description 3:%n%s%n%n", builder.build().toString(TiffIFD.StringFormat.NORMAL));
    }
}
